# Change these first
owner: nchandra75 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: NPTEL
    url: https://nptel.ac.in
  - name: NPTEL Archive
    url: https://archive.nptel.ac.in
  - name: Internal Dashboard
    url: $URL_INT_DASHBOARD
  - name: EE Moodle
    url: https://eex.dev.iitm.ac.in
  - name: Jupyter server
    url: https://jup.dev.iitm.ac.in

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Status page for NPTEL and related sites"
  introMessage: This is a status page for sites managed on the NPTEL servers.
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
  
